### ISSUE TITLE
searchWrapper removeEventListener()

### ISSUE THREAD

**Issue by jogamod** [srigar/multiselect-react-dropdown#1]
I'm getting error on `searchWrapper.current.removeEventListener()` : `Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 0 present.`

**Comment by srigar** [comment]
Fixed in `1.1.0`. Use the latest version.

**Comment by jogamod** [comment]
I'm still getting this error, beacause in `build` -> `index.js` it's still `searchWrapper.current.removeEventListener()` and not `searchWrapper.current.removeEventListener('click', listenerCallback)`

**Comment by srigar** [comment]
Hey, Pls try to take version 1.1.2

**Comment by jogamod** [comment]
`Uncaught ReferenceError: listenerCallback is not defined` in `build` -> `index.js` on both `searchWrapper.current.addEventListener` and `searchWrapper.current.removeEventListener` :cry:

**Comment by srigar** [comment]
Sorry, Updated in demo. Working fine in version 1.1.4. If it is not working reopen it.
