### ISSUE TITLE
Disable chrome autocomplete property

### ISSUE THREAD

**Issue by lirazUp9** [srigar/multiselect-react-dropdown#53]
disable chrome autocomplete opening on "serachBox" input focus

**Comment by srigar** [comment]
changes available in v1.5.6

**Comment by danpalmer** [comment]
@srigar I've just noticed that this is an invalid property according to `react-dom`, warnings suggest it should be `autoComplete`.

![Screenshot 2020-07-02 at 12 14 47](https://user-images.githubusercontent.com/202400/86352397-a423a000-bc5d-11ea-82ca-e5d467ae519c.png)

**Comment by srigar** [comment]
@danpalmer Thanks. Warning addressed in v1.5.7

**Comment by panktip15** [comment]
@srigar looks like I can still see the autoComplete pop up, is there a way we can set it to `autoComplete="chrome-off"`
![image](https://user-images.githubusercontent.com/30152454/124308500-992c7580-db26-11eb-82ba-8ecf7a111c1d.png)
